services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    # container_name: app_sample_db
    environment:
      - POSTGRES_USER:david
      - POSTGRES_PASSWORD:davidlh
      - POSTGRES_DB:db_states
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    env_file:
      - .env
  
  app:
    build:
      context: .
    #container_name: app_sample
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - 3000:3000